# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true

# Ignore files that don't need coverage
ignore:
  - "tests/**/*"
  - "**/__pycache__/**"
  - "**/conftest.py"
  - "setup.py"
  - "docs/**/*"
  - "installer/**/*"
  - "web/**/*"

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

# Flag definitions
flags:
  backend:
    paths:
      - weather_app/
    carryforward: true
